import { relations, sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  uuid,
  timestamp,
  date,
  jsonb,
  integer,
  bigint,
  boolean,
  numeric,
  index,
  uniqueIndex,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { users } from "./identity";
import { businesses } from "./businesses";
import { clients } from "./clients";
import { journalEntries } from "./ledger";

// IL invoice types per ITA spec. Each maps to a different sequence + form
// behaviour. `self_invoice` covers reverse-charge VAT (חשבונית עצמית).
export const invoiceTypeEnum = pgEnum("invoice_type", [
  "tax_invoice",
  "tax_invoice_receipt",
  "receipt",
  "credit_note",
  "proforma",
  "debit_note",
  "self_invoice",
]);

// 4-path allocation-number lifecycle (Plan v4 § Invoice clearance).
//  not_required        — pre-threshold invoice or exempt type
//  required_not_assigned — over threshold, waiting on operator
//  manual_pasted       — operator pasted SHAAM allocation by hand
//  partner_issued      — issued via Green Invoice / iCount / EZCount
//  processor_synced    — generated by a payment-processor sync
//  direct_shaam        — issued directly against SHAAM (future, post-cert)
export const allocationStatusEnum = pgEnum("allocation_status", [
  "not_required",
  "required_not_assigned",
  "manual_pasted",
  "partner_issued",
  "processor_synced",
  "direct_shaam",
]);

// Issuance path. `internal` = we generated the document via our own
// sequence. Everything else is an external provider that owns the
// numbering / allocation lifecycle.
export const providerKindEnum = pgEnum("provider_kind", [
  "internal",
  "greenInvoice",
  "iCount",
  "ezCount",
  "hyp",
  "grow",
  "payplus",
  "direct_shaam",
]);

export const invoices = pgTable(
  "invoices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    // Nullable for `self_invoice` reverse-charge cases where the supplier
    // is on the other side of the document.
    clientId: uuid("client_id").references(() => clients.id, {
      onDelete: "restrict",
    }),
    invoiceType: invoiceTypeEnum("invoice_type").notNull(),
    sequentialNumber: integer("sequential_number").notNull(),
    // Self-reference for credit_note → tax_invoice and debit_note → tax_invoice.
    parentInvoiceId: uuid("parent_invoice_id").references(
      (): AnyPgColumn => invoices.id,
      { onDelete: "restrict" },
    ),
    cancelledAt: timestamp("cancelled_at"),
    cancellationReason: text("cancellation_reason"),
    issueDate: date("issue_date").notNull(),
    dueDate: date("due_date"),
    subtotalMinor: bigint("subtotal_minor", { mode: "bigint" }).notNull(),
    vatMinor: bigint("vat_minor", { mode: "bigint" }).notNull(),
    totalMinor: bigint("total_minor", { mode: "bigint" }).notNull(),
    // VAT rate the entire invoice was issued at. Per-line override is
    // captured on invoice_line_items.vat_rate.
    vatRate: numeric("vat_rate", { precision: 4, scale: 2 }).notNull(),
    currencyAtIssue: text("currency_at_issue").notNull().default("ILS"),
    fxRateAtIssue: numeric("fx_rate_at_issue", { precision: 18, scale: 8 }),
    allocationNumber: text("allocation_number"),
    allocationStatus: allocationStatusEnum("allocation_status")
      .notNull()
      .default("not_required"),
    // Frozen at INSERT based on dated rule (threshold = ₪25k pre 2026-06-01,
    // ₪5k post). App enforces; never recompute after issue.
    allocationRequiredAtIssue: boolean("allocation_required_at_issue").notNull(),
    providerKind: providerKindEnum("provider_kind").notNull().default("internal"),
    externalInvoiceId: text("external_invoice_id"),
    pcn874ExportedAt: timestamp("pcn874_exported_at"),
    linkedJournalEntryId: uuid("linked_journal_entry_id").references(
      () => journalEntries.id,
      { onDelete: "set null" },
    ),
    notesHe: text("notes_he"),
    notesEn: text("notes_en"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
    deletedAt: timestamp("deleted_at"),
  },
  (table) => [
    // Conditional uniqueness: enforce no-gap policy ONLY for internal
    // sequence numbers and only for non-cancelled rows. Cancelled rows
    // free up their slot so a follow-up issue with the same number
    // succeeds (still tracked in invoice_sequence_audit).
    uniqueIndex("invoices_internal_sequence_idx")
      .on(table.businessId, table.invoiceType, table.sequentialNumber)
      .where(
        sql`provider_kind = 'internal' AND cancelled_at IS NULL`,
      ),
    index("invoices_business_issue_date_idx").on(
      table.businessId,
      table.issueDate,
    ),
    index("invoices_client_idx").on(table.clientId),
    index("invoices_allocation_status_idx").on(table.allocationStatus),
  ],
);

export const invoiceLineItems = pgTable(
  "invoice_line_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    description: text("description").notNull(),
    quantity: numeric("quantity", { precision: 18, scale: 4 }).notNull(),
    unitPriceMinor: bigint("unit_price_minor", { mode: "bigint" }).notNull(),
    vatRate: numeric("vat_rate", { precision: 4, scale: 2 }).notNull(),
    lineTotalMinor: bigint("line_total_minor", { mode: "bigint" }).notNull(),
    // FK target is a future inventory table; deliberately nullable + no FK
    // declared so this column stays valid even before inventory ships.
    linkedInventoryItemId: uuid("linked_inventory_item_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    uniqueIndex("invoice_line_items_position_idx").on(
      table.invoiceId,
      table.position,
    ),
  ],
);

export const invoiceSequenceOutcomeEnum = pgEnum(
  "invoice_sequence_outcome",
  ["committed", "rolled_back", "gap_detected"],
);

// Append-only audit of every sequence allocation attempt — needed because
// IL ITA expects a documented explanation of any gap in a no-gap series.
export const invoiceSequenceAudit = pgTable(
  "invoice_sequence_audit",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    invoiceType: invoiceTypeEnum("invoice_type").notNull(),
    attemptedSequence: integer("attempted_sequence").notNull(),
    outcome: invoiceSequenceOutcomeEnum("outcome").notNull(),
    committedInvoiceId: uuid("committed_invoice_id").references(
      () => invoices.id,
      { onDelete: "set null" },
    ),
    attemptedAt: timestamp("attempted_at").defaultNow().notNull(),
    actorUserId: uuid("actor_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
  },
  (table) => [
    index("invoice_sequence_audit_business_type_time_idx").on(
      table.businessId,
      table.invoiceType,
      table.attemptedAt,
    ),
  ],
);

export type RecurringInvoiceTemplateJsonb = {
  invoice?: Record<string, unknown>;
  lineItems?: Array<Record<string, unknown>>;
};

export const recurringInvoiceTemplates = pgTable(
  "recurring_invoice_templates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    clientId: uuid("client_id")
      .notNull()
      .references(() => clients.id, { onDelete: "restrict" }),
    templateJsonb: jsonb("template_jsonb")
      .$type<RecurringInvoiceTemplateJsonb>()
      .notNull()
      .default(sql`'{}'::jsonb`),
    cadence: text("cadence").notNull(),
    nextRunAt: timestamp("next_run_at"),
    lastRunAt: timestamp("last_run_at"),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("recurring_invoice_templates_business_idx").on(table.businessId),
    index("recurring_invoice_templates_next_run_idx")
      .on(table.nextRunAt)
      .where(sql`active = true`),
  ],
);

export const invoiceReminders = pgTable(
  "invoice_reminders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),
    scheduledAt: timestamp("scheduled_at").notNull(),
    sentAt: timestamp("sent_at"),
    // Symbolic names: pre_due / overdue_3d / overdue_7d / overdue_30d.
    kind: text("kind").notNull(),
    emailMessageId: text("email_message_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("invoice_reminders_pending_idx")
      .on(table.scheduledAt)
      .where(sql`sent_at IS NULL`),
    index("invoice_reminders_invoice_idx").on(table.invoiceId),
  ],
);

export const invoicesRelations = relations(invoices, ({ one, many }) => ({
  business: one(businesses, {
    fields: [invoices.businessId],
    references: [businesses.id],
  }),
  client: one(clients, {
    fields: [invoices.clientId],
    references: [clients.id],
  }),
  linkedJournalEntry: one(journalEntries, {
    fields: [invoices.linkedJournalEntryId],
    references: [journalEntries.id],
  }),
  lineItems: many(invoiceLineItems),
  reminders: many(invoiceReminders),
}));

export const invoiceLineItemsRelations = relations(
  invoiceLineItems,
  ({ one }) => ({
    invoice: one(invoices, {
      fields: [invoiceLineItems.invoiceId],
      references: [invoices.id],
    }),
  }),
);

export const invoiceSequenceAuditRelations = relations(
  invoiceSequenceAudit,
  ({ one }) => ({
    business: one(businesses, {
      fields: [invoiceSequenceAudit.businessId],
      references: [businesses.id],
    }),
    committedInvoice: one(invoices, {
      fields: [invoiceSequenceAudit.committedInvoiceId],
      references: [invoices.id],
    }),
    actor: one(users, {
      fields: [invoiceSequenceAudit.actorUserId],
      references: [users.id],
    }),
  }),
);

export const recurringInvoiceTemplatesRelations = relations(
  recurringInvoiceTemplates,
  ({ one }) => ({
    business: one(businesses, {
      fields: [recurringInvoiceTemplates.businessId],
      references: [businesses.id],
    }),
    client: one(clients, {
      fields: [recurringInvoiceTemplates.clientId],
      references: [clients.id],
    }),
  }),
);

export const invoiceRemindersRelations = relations(
  invoiceReminders,
  ({ one }) => ({
    invoice: one(invoices, {
      fields: [invoiceReminders.invoiceId],
      references: [invoices.id],
    }),
  }),
);
