import { relations, sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  uuid,
  timestamp,
  date,
  jsonb,
  integer,
  bigint,
  boolean,
  numeric,
  index,
  uniqueIndex,
  check,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { users } from "./identity";
import { businesses } from "./businesses";
import { dataEncryptionKeys } from "./ops";

// Bank / cash / credit card / loan / equity (drawing) / other. The "other"
// fallback covers PayPal-balance-style holdings until we model them properly.
export const financialAccountKindEnum = pgEnum("financial_account_kind", [
  "bank",
  "cash",
  "credit_card",
  "loan",
  "equity",
  "other",
]);

export const financialAccounts = pgTable(
  "financial_accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    kind: financialAccountKindEnum("kind").notNull(),
    name: text("name").notNull(),
    currency: text("currency").notNull().default("ILS"),
    openingBalanceMinor: bigint("opening_balance_minor", { mode: "bigint" })
      .notNull()
      .default(sql`0`),
    closedAt: timestamp("closed_at"),
    externalAccountRef: text("external_account_ref"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("financial_accounts_business_idx").on(table.businessId),
  ],
);

// Where a journal entry came from. `manual` = user-entered via UI;
// `invoice` / `payment` = generated by app code at the time of issue;
// `bank_import` / `processor_sync` = derived from external feeds;
// `payroll_run` = wage / withholding postings;
// `year_end_close` = closing entries (immutable, written via service role);
// `fx_revaluation` = period-end FX adjustment runs.
export const journalEntrySourceEnum = pgEnum("journal_entry_source", [
  "manual",
  "invoice",
  "payment",
  "bank_import",
  "processor_sync",
  "payroll_run",
  "year_end_close",
  "fx_revaluation",
]);

export type JournalEntryMetadataJsonb = Record<string, unknown>;

export const journalEntries = pgTable(
  "journal_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    entryDate: date("entry_date").notNull(),
    description: text("description"),
    source: journalEntrySourceEnum("source").notNull(),
    postedAt: timestamp("posted_at").defaultNow().notNull(),
    // A reversal points at the original entry it cancels. Reversal of a
    // reversal is allowed but discouraged; app code at the ledger layer
    // forbids closing-period reversals.
    reversedById: uuid("reversed_by_id").references(
      (): AnyPgColumn => journalEntries.id,
      { onDelete: "set null" },
    ),
    createdByUserId: uuid("created_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    metadataJsonb: jsonb("metadata_jsonb")
      .$type<JournalEntryMetadataJsonb>()
      .notNull()
      .default(sql`'{}'::jsonb`),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("journal_entries_business_date_idx").on(
      table.businessId,
      table.entryDate,
    ),
    index("journal_entries_source_idx").on(table.source),
  ],
);

// Every line is either a debit OR a credit, never both, never zero.
// Per-entry sum-debit-equals-sum-credit invariant is enforced by a
// SECURITY DEFINER trigger added in 0005_rls_layer2.sql.
export const journalLines = pgTable(
  "journal_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    entryId: uuid("entry_id")
      .notNull()
      .references(() => journalEntries.id, { onDelete: "cascade" }),
    // References chart_of_accounts.code via (businessId, accountCode); FK
    // is not declarable at DB level because chart_of_accounts has a
    // composite PK (business_id, code) and one side is nullable for the
    // seeded standard codes — enforced at the app layer.
    accountCode: text("account_code").notNull(),
    debitMinor: bigint("debit_minor", { mode: "bigint" })
      .notNull()
      .default(sql`0`),
    creditMinor: bigint("credit_minor", { mode: "bigint" })
      .notNull()
      .default(sql`0`),
    currency: text("currency").notNull().default("ILS"),
    // FX rate at posting time for non-ILS lines. NULL for ILS-only lines.
    fxRate: numeric("fx_rate", { precision: 18, scale: 8 }),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("journal_lines_entry_idx").on(table.entryId),
    index("journal_lines_account_code_idx").on(table.accountCode),
    // XOR: each line is debit-only or credit-only.
    check(
      "journal_lines_xor_debit_credit",
      sql`(${table.debitMinor} > 0 AND ${table.creditMinor} = 0) OR (${table.debitMinor} = 0 AND ${table.creditMinor} > 0)`,
    ),
    // Belt-and-braces: never negative, never both zero.
    check(
      "journal_lines_nonnegative_nonzero",
      sql`${table.debitMinor} >= 0 AND ${table.creditMinor} >= 0 AND (${table.debitMinor} + ${table.creditMinor} > 0)`,
    ),
  ],
);

// Standard IL CPA chart-of-accounts.
//
// business_id = NULL means a system-seeded standard code that every
// business can SELECT but only the service role can INSERT/UPDATE/DELETE.
// business_id = <uuid> means a per-business custom code that overrides
// or extends the standard set. Application code resolving a code does
// the per-business lookup first, then falls back to NULL business_id
// (see lib/ledger/chartOfAccounts.ts in Phase C).
//
// Uniqueness is enforced via two partial unique indexes — the composite
// PK route can't carry NULL business_id (PK columns are NOT NULL by
// definition). A surrogate uuid id keeps the row addressable.
export const chartOfAccountsTypeEnum = pgEnum("chart_of_accounts_type", [
  "asset",
  "liability",
  "equity",
  "income",
  "expense",
]);

export const chartOfAccounts = pgTable(
  "chart_of_accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id").references(() => businesses.id, {
      onDelete: "cascade",
    }),
    code: text("code").notNull(),
    nameHe: text("name_he"),
    nameEn: text("name_en"),
    type: chartOfAccountsTypeEnum("type").notNull(),
    form6111Line: text("form_6111_line"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    // One row per (business_id, code) for per-business custom codes.
    uniqueIndex("chart_of_accounts_business_code_idx")
      .on(table.businessId, table.code)
      .where(sql`business_id IS NOT NULL`),
    // One row per standard code (business_id NULL).
    uniqueIndex("chart_of_accounts_standard_code_idx")
      .on(table.code)
      .where(sql`business_id IS NULL`),
    // Lookup index for application resolution (code → row).
    index("chart_of_accounts_code_idx").on(table.code),
  ],
);

export const openingBalances = pgTable(
  "opening_balances",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    accountCode: text("account_code").notNull(),
    fiscalYear: integer("fiscal_year").notNull(),
    balanceMinor: bigint("balance_minor", { mode: "bigint" }).notNull(),
    currency: text("currency").notNull().default("ILS"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    uniqueIndex("opening_balances_unique_idx").on(
      table.businessId,
      table.accountCode,
      table.fiscalYear,
    ),
  ],
);

// Per-year close stamp. Once a row exists the period is considered closed
// and journal_entries.entry_date inside it are immutable from the app
// surface (app_period_is_closed() helper). Closing entries themselves
// are written via the service role bypass.
export const yearEndCloses = pgTable(
  "year_end_closes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    fiscalYear: integer("fiscal_year").notNull(),
    closedAt: timestamp("closed_at").defaultNow().notNull(),
    closedByUserId: uuid("closed_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    closeJournalEntryId: uuid("close_journal_entry_id").references(
      () => journalEntries.id,
      { onDelete: "restrict" },
    ),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("year_end_closes_unique_idx").on(
      table.businessId,
      table.fiscalYear,
    ),
  ],
);

export const financialStatementKindEnum = pgEnum("financial_statement_kind", [
  "balance_sheet",
  "profit_loss",
  "cash_flow",
]);

export type FinancialStatementTotalsJsonb = Record<string, unknown>;

export const financialStatements = pgTable(
  "financial_statements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    kind: financialStatementKindEnum("kind").notNull(),
    periodStart: date("period_start").notNull(),
    periodEnd: date("period_end").notNull(),
    generatedAt: timestamp("generated_at").defaultNow().notNull(),
    totalsJsonb: jsonb("totals_jsonb")
      .$type<FinancialStatementTotalsJsonb>()
      .notNull()
      .default(sql`'{}'::jsonb`),
    fileCiphertext: text("file_ciphertext"),
    fileKeyId: uuid("file_key_id").references(() => dataEncryptionKeys.id, {
      onDelete: "restrict",
    }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("financial_statements_business_period_idx").on(
      table.businessId,
      table.periodEnd,
    ),
  ],
);

export type FxRevaluationRatesJsonb = Record<string, string>;

export const fxRevaluationRuns = pgTable(
  "fx_revaluation_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => businesses.id, { onDelete: "cascade" }),
    periodEnd: date("period_end").notNull(),
    ranAt: timestamp("ran_at").defaultNow().notNull(),
    adjustmentEntryId: uuid("adjustment_entry_id").references(
      () => journalEntries.id,
      { onDelete: "restrict" },
    ),
    fxRatesJsonb: jsonb("fx_rates_jsonb")
      .$type<FxRevaluationRatesJsonb>()
      .notNull()
      .default(sql`'{}'::jsonb`),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("fx_revaluation_runs_business_period_idx").on(
      table.businessId,
      table.periodEnd,
    ),
  ],
);

export const financialAccountsRelations = relations(
  financialAccounts,
  ({ one }) => ({
    business: one(businesses, {
      fields: [financialAccounts.businessId],
      references: [businesses.id],
    }),
  }),
);

export const journalEntriesRelations = relations(
  journalEntries,
  ({ one, many }) => ({
    business: one(businesses, {
      fields: [journalEntries.businessId],
      references: [businesses.id],
    }),
    createdByUser: one(users, {
      fields: [journalEntries.createdByUserId],
      references: [users.id],
    }),
    lines: many(journalLines),
  }),
);

export const journalLinesRelations = relations(journalLines, ({ one }) => ({
  entry: one(journalEntries, {
    fields: [journalLines.entryId],
    references: [journalEntries.id],
  }),
}));

export const chartOfAccountsRelations = relations(
  chartOfAccounts,
  ({ one }) => ({
    business: one(businesses, {
      fields: [chartOfAccounts.businessId],
      references: [businesses.id],
    }),
  }),
);

export const openingBalancesRelations = relations(
  openingBalances,
  ({ one }) => ({
    business: one(businesses, {
      fields: [openingBalances.businessId],
      references: [businesses.id],
    }),
  }),
);

export const yearEndClosesRelations = relations(yearEndCloses, ({ one }) => ({
  business: one(businesses, {
    fields: [yearEndCloses.businessId],
    references: [businesses.id],
  }),
  closedByUser: one(users, {
    fields: [yearEndCloses.closedByUserId],
    references: [users.id],
  }),
  closeJournalEntry: one(journalEntries, {
    fields: [yearEndCloses.closeJournalEntryId],
    references: [journalEntries.id],
  }),
}));

export const financialStatementsRelations = relations(
  financialStatements,
  ({ one }) => ({
    business: one(businesses, {
      fields: [financialStatements.businessId],
      references: [businesses.id],
    }),
  }),
);

export const fxRevaluationRunsRelations = relations(
  fxRevaluationRuns,
  ({ one }) => ({
    business: one(businesses, {
      fields: [fxRevaluationRuns.businessId],
      references: [businesses.id],
    }),
    adjustmentEntry: one(journalEntries, {
      fields: [fxRevaluationRuns.adjustmentEntryId],
      references: [journalEntries.id],
    }),
  }),
);
